export const INVALID_CLASSNAME = "is-invalid";
export const FORM_LABEL_CLASSNAME = "form-label";
export const SELECT_CLASSNAME = "form-select";

export const RADIO_BUTTON_WRAPPER_CLASSNAME = "form-check";
export const RADIO_BUTTON_CLASSNAME = `${RADIO_BUTTON_WRAPPER_CLASSNAME}-input`;
export const RADIO_BUTTON_LABEL_CLASSNAME = `${RADIO_BUTTON_WRAPPER_CLASSNAME}-label`;
export const RADIO_BUTTON_INLINE_CLASSNAME = `${RADIO_BUTTON_WRAPPER_CLASSNAME}-inline`;

export const CHECKBOX_WRAPPER_CLASSNAME = "form-check";
export const CHECKBOX_CLASSNAME = `${CHECKBOX_WRAPPER_CLASSNAME}-input`;
export const CHECKBOX_LABEL_CLASSNAME = `${CHECKBOX_WRAPPER_CLASSNAME}-label`;
export const CHECKBOX_INLINE_CLASSNAME = `${CHECKBOX_WRAPPER_CLASSNAME}-inline`;
